FROM node:22-alpine AS client-builder
WORKDIR /app/client

COPY client/package*.json ./
RUN npm ci

COPY client/ ./
RUN npm run build


FROM node:22-alpine AS server-builder
WORKDIR /app

COPY server/package*.json ./
RUN npm ci

COPY server/ ./
RUN DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy" npx prisma generate
RUN npm run build


FROM node:22-alpine AS runtime
WORKDIR /app

ENV NODE_ENV=production

COPY --from=server-builder /app/dist ./dist
COPY --from=server-builder /app/node_modules ./node_modules
COPY --from=server-builder /app/package.json ./package.json
COPY --from=server-builder /app/prisma ./prisma

# Path ini cocok dengan path.join(__dirname, "../../client/dist")
COPY --from=client-builder /app/client/dist /client/dist

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run start"]